version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
